"use client";

import { startTransition, useEffect, useState } from "react";

import ChatComposer from "@/components/chat/ChatComposer";
import ChatHeader from "@/components/chat/ChatHeader";
import MessageList from "@/components/chat/MessageList";
import SectionNav from "@/components/navigation/SectionNav";
import UserMenu from "@/components/navigation/UserMenu";
import RecommendationsPanel from "@/components/recommendations/RecommendationsPanel";
import { useChatSession } from "@/hooks/useChatSession";

const PlaceholderPanel = ({ label }: { label: string }) => (
  <section className="rounded-3xl border border-dashed border-zinc-200 bg-white/70 px-6 py-16 text-center backdrop-blur dark:border-indigo-700/60 dark:bg-indigo-950/60">
    <p className="text-sm font-semibold uppercase tracking-wide text-indigo-500">
      {label}
    </p>
    <h2 className="mt-4 text-2xl font-semibold text-zinc-900">Coming soon</h2>
    <p className="mt-2 text-sm text-zinc-500">
      This surface will visualize graph hops, collaborations, and influence
      chains generated by pmLLM.
    </p>
  </section>
);

const ChatWorkspace = () => {
  const {
    messages,
    inputValue,
    isResponding,
    isBootstrapping,
    isReady,
    error,
    endOfMessagesRef,
    handleInputChange,
    handleSubmit,
    retrySession,
  } = useChatSession();
  const [activeSection, setActiveSection] = useState("chat");
  const [themeMode, setThemeMode] = useState<"light" | "dark">("light");
  const isChatView = activeSection === "chat";

  useEffect(() => {
    if (typeof window === "undefined") return;
    const stored = window.localStorage.getItem("pmllm-theme");
    const resolved: "light" | "dark" =
      stored === "light" || stored === "dark"
        ? stored
        : window.matchMedia("(prefers-color-scheme: dark)").matches
          ? "dark"
          : "light";

    startTransition(() => {
      setThemeMode(resolved);
    });
  }, []);

  useEffect(() => {
    if (typeof document === "undefined" || typeof window === "undefined") return;
    const root = document.documentElement;
    root.dataset.theme = themeMode;
    root.classList.toggle("dark", themeMode === "dark");
    window.localStorage.setItem("pmllm-theme", themeMode);
  }, [themeMode]);

  const handleToggleTheme = () => {
    setThemeMode((prev) => (prev === "light" ? "dark" : "light"));
  };

  const getHeaderTitle = () => {
    switch (activeSection) {
      case "chat":
        return "Chat";
      case "recommendations":
        return "Recommendations";
      case "connections":
        return "Connections";
      default:
        return "Chat";
    }
  };

  return (
    <div className="relative flex min-h-screen flex-col bg-white/95 text-zinc-900 backdrop-blur dark:bg-[#101430]/95 dark:text-indigo-100">
      <ChatHeader
        title={getHeaderTitle()}
        themeMode={themeMode}
        onToggleTheme={handleToggleTheme}
      />

      <main className="flex-1 pt-24">
        <div className="mx-auto flex h-full w-full max-w-5xl flex-col gap-10 px-6 py-8">
          {(() => {
            if (activeSection === "chat") {
              return (
                <section className="flex flex-1 flex-col">
                  <MessageList
                    messages={messages}
                    isResponding={isResponding}
                    isBootstrapping={isBootstrapping}
                    error={error}
                    onRetry={retrySession}
                    endOfMessagesRef={endOfMessagesRef}
                  />
                </section>
              );
            }

            if (activeSection === "recommendations") {
              return <RecommendationsPanel />;
            }

            return <PlaceholderPanel label="Connections" />;
          })()}
        </div>
      </main>

      {isChatView && (
        <ChatComposer
          inputValue={inputValue}
          isResponding={isResponding}
          isReady={isReady}
          isBootstrapping={isBootstrapping}
          onInputChange={handleInputChange}
          onSubmit={handleSubmit}
        />
      )}

      <div className="fixed bottom-6 left-6 z-40 flex max-w-xs flex-col gap-3">
        <SectionNav activeId={activeSection} onSelect={setActiveSection} />
        <UserMenu />
      </div>
    </div>
  );
};

export default ChatWorkspace;
