"use client";

import { useState } from "react";

import ChatComposer from "@/components/chat/ChatComposer";
import ChatHeader from "@/components/chat/ChatHeader";
import MessageList from "@/components/chat/MessageList";
import SectionNav from "@/components/navigation/SectionNav";
import UserMenu from "@/components/navigation/UserMenu";
import RecommendationsPanel from "@/components/recommendations/RecommendationsPanel";
import { useChatSession } from "@/hooks/useChatSession";

const PlaceholderPanel = ({ label }: { label: string }) => (
  <section className="rounded-3xl border border-dashed border-zinc-200 bg-white/70 px-6 py-16 text-center">
    <p className="text-sm font-semibold uppercase tracking-wide text-blue-500">
      {label}
    </p>
    <h2 className="mt-4 text-2xl font-semibold text-zinc-900">Coming soon</h2>
    <p className="mt-2 text-sm text-zinc-500">
      This surface will visualize graph hops, collaborations, and influence
      chains generated by pmLLM.
    </p>
  </section>
);

const ChatWorkspace = () => {
  const {
    messages,
    inputValue,
    isResponding,
    endOfMessagesRef,
    handleInputChange,
    handleSubmit,
  } = useChatSession();
  const [activeSection, setActiveSection] = useState("chat");
  const isChatView = activeSection === "chat";

  return (
    <div className="relative flex min-h-screen flex-col bg-white text-zinc-900">
      <ChatHeader />

      <main className="flex-1">
        <div className="mx-auto flex h-full w-full max-w-5xl flex-col gap-10 px-6 py-8">
          {(() => {
            if (activeSection === "chat") {
              return (
                <section className="flex flex-1 flex-col">
                  <MessageList
                    messages={messages}
                    isResponding={isResponding}
                    endOfMessagesRef={endOfMessagesRef}
                  />
                </section>
              );
            }

            if (activeSection === "recommendations") {
              return <RecommendationsPanel />;
            }

            return <PlaceholderPanel label="Connections" />;
          })()}
        </div>
      </main>

      {isChatView && (
        <ChatComposer
          inputValue={inputValue}
          isResponding={isResponding}
          onInputChange={handleInputChange}
          onSubmit={handleSubmit}
        />
      )}

      <div className="fixed bottom-6 left-6 z-40 flex max-w-xs flex-col gap-3">
        <SectionNav activeId={activeSection} onSelect={setActiveSection} />
        <UserMenu />
      </div>
    </div>
  );
};

export default ChatWorkspace;
